// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: namelti.proto

#ifndef PROTOBUF_namelti_2eproto__INCLUDED
#define PROTOBUF_namelti_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace namelti {
namespace server {
class NameltiTranscriptRequest;
class NameltiTranscriptRequestDefaultTypeInternal;
extern NameltiTranscriptRequestDefaultTypeInternal _NameltiTranscriptRequest_default_instance_;
class NameltiTranscriptRequests;
class NameltiTranscriptRequestsDefaultTypeInternal;
extern NameltiTranscriptRequestsDefaultTypeInternal _NameltiTranscriptRequests_default_instance_;
class NameltiTranscriptResponse;
class NameltiTranscriptResponseDefaultTypeInternal;
extern NameltiTranscriptResponseDefaultTypeInternal _NameltiTranscriptResponse_default_instance_;
class NameltiTranscriptResponses;
class NameltiTranscriptResponsesDefaultTypeInternal;
extern NameltiTranscriptResponsesDefaultTypeInternal _NameltiTranscriptResponses_default_instance_;
class ResultList;
class ResultListDefaultTypeInternal;
extern ResultListDefaultTypeInternal _ResultList_default_instance_;
class ResultList_Result;
class ResultList_ResultDefaultTypeInternal;
extern ResultList_ResultDefaultTypeInternal _ResultList_Result_default_instance_;
}  // namespace server
}  // namespace namelti

namespace namelti {
namespace server {

namespace protobuf_namelti_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_namelti_2eproto

// ===================================================================

class NameltiTranscriptRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:namelti.server.NameltiTranscriptRequest) */ {
 public:
  NameltiTranscriptRequest();
  virtual ~NameltiTranscriptRequest();

  NameltiTranscriptRequest(const NameltiTranscriptRequest& from);

  inline NameltiTranscriptRequest& operator=(const NameltiTranscriptRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const NameltiTranscriptRequest& default_instance();

  static inline const NameltiTranscriptRequest* internal_default_instance() {
    return reinterpret_cast<const NameltiTranscriptRequest*>(
               &_NameltiTranscriptRequest_default_instance_);
  }

  void Swap(NameltiTranscriptRequest* other);

  // implements Message ----------------------------------------------

  inline NameltiTranscriptRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  NameltiTranscriptRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const NameltiTranscriptRequest& from);
  void MergeFrom(const NameltiTranscriptRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(NameltiTranscriptRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string query = 1;
  void clear_query();
  static const int kQueryFieldNumber = 1;
  const ::std::string& query() const;
  void set_query(const ::std::string& value);
  #if LANG_CXX11
  void set_query(::std::string&& value);
  #endif
  void set_query(const char* value);
  void set_query(const char* value, size_t size);
  ::std::string* mutable_query();
  ::std::string* release_query();
  void set_allocated_query(::std::string* query);

  // @@protoc_insertion_point(class_scope:namelti.server.NameltiTranscriptRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr query_;
  mutable int _cached_size_;
  friend struct  protobuf_namelti_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class NameltiTranscriptRequests : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:namelti.server.NameltiTranscriptRequests) */ {
 public:
  NameltiTranscriptRequests();
  virtual ~NameltiTranscriptRequests();

  NameltiTranscriptRequests(const NameltiTranscriptRequests& from);

  inline NameltiTranscriptRequests& operator=(const NameltiTranscriptRequests& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const NameltiTranscriptRequests& default_instance();

  static inline const NameltiTranscriptRequests* internal_default_instance() {
    return reinterpret_cast<const NameltiTranscriptRequests*>(
               &_NameltiTranscriptRequests_default_instance_);
  }

  void Swap(NameltiTranscriptRequests* other);

  // implements Message ----------------------------------------------

  inline NameltiTranscriptRequests* New() const PROTOBUF_FINAL { return New(NULL); }

  NameltiTranscriptRequests* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const NameltiTranscriptRequests& from);
  void MergeFrom(const NameltiTranscriptRequests& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(NameltiTranscriptRequests* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string queries = 1;
  int queries_size() const;
  void clear_queries();
  static const int kQueriesFieldNumber = 1;
  const ::std::string& queries(int index) const;
  ::std::string* mutable_queries(int index);
  void set_queries(int index, const ::std::string& value);
  void set_queries(int index, const char* value);
  void set_queries(int index, const char* value, size_t size);
  ::std::string* add_queries();
  void add_queries(const ::std::string& value);
  void add_queries(const char* value);
  void add_queries(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& queries() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_queries();

  // @@protoc_insertion_point(class_scope:namelti.server.NameltiTranscriptRequests)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::std::string> queries_;
  mutable int _cached_size_;
  friend struct  protobuf_namelti_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ResultList_Result : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:namelti.server.ResultList.Result) */ {
 public:
  ResultList_Result();
  virtual ~ResultList_Result();

  ResultList_Result(const ResultList_Result& from);

  inline ResultList_Result& operator=(const ResultList_Result& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ResultList_Result& default_instance();

  static inline const ResultList_Result* internal_default_instance() {
    return reinterpret_cast<const ResultList_Result*>(
               &_ResultList_Result_default_instance_);
  }

  void Swap(ResultList_Result* other);

  // implements Message ----------------------------------------------

  inline ResultList_Result* New() const PROTOBUF_FINAL { return New(NULL); }

  ResultList_Result* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ResultList_Result& from);
  void MergeFrom(const ResultList_Result& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ResultList_Result* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string yomi = 1;
  void clear_yomi();
  static const int kYomiFieldNumber = 1;
  const ::std::string& yomi() const;
  void set_yomi(const ::std::string& value);
  #if LANG_CXX11
  void set_yomi(::std::string&& value);
  #endif
  void set_yomi(const char* value);
  void set_yomi(const char* value, size_t size);
  ::std::string* mutable_yomi();
  ::std::string* release_yomi();
  void set_allocated_yomi(::std::string* yomi);

  // float score = 2;
  void clear_score();
  static const int kScoreFieldNumber = 2;
  float score() const;
  void set_score(float value);

  // @@protoc_insertion_point(class_scope:namelti.server.ResultList.Result)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr yomi_;
  float score_;
  mutable int _cached_size_;
  friend struct  protobuf_namelti_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ResultList : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:namelti.server.ResultList) */ {
 public:
  ResultList();
  virtual ~ResultList();

  ResultList(const ResultList& from);

  inline ResultList& operator=(const ResultList& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ResultList& default_instance();

  static inline const ResultList* internal_default_instance() {
    return reinterpret_cast<const ResultList*>(
               &_ResultList_default_instance_);
  }

  void Swap(ResultList* other);

  // implements Message ----------------------------------------------

  inline ResultList* New() const PROTOBUF_FINAL { return New(NULL); }

  ResultList* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ResultList& from);
  void MergeFrom(const ResultList& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ResultList* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef ResultList_Result Result;

  // accessors -------------------------------------------------------

  // repeated .namelti.server.ResultList.Result results = 1;
  int results_size() const;
  void clear_results();
  static const int kResultsFieldNumber = 1;
  const ::namelti::server::ResultList_Result& results(int index) const;
  ::namelti::server::ResultList_Result* mutable_results(int index);
  ::namelti::server::ResultList_Result* add_results();
  ::google::protobuf::RepeatedPtrField< ::namelti::server::ResultList_Result >*
      mutable_results();
  const ::google::protobuf::RepeatedPtrField< ::namelti::server::ResultList_Result >&
      results() const;

  // @@protoc_insertion_point(class_scope:namelti.server.ResultList)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::namelti::server::ResultList_Result > results_;
  mutable int _cached_size_;
  friend struct  protobuf_namelti_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class NameltiTranscriptResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:namelti.server.NameltiTranscriptResponse) */ {
 public:
  NameltiTranscriptResponse();
  virtual ~NameltiTranscriptResponse();

  NameltiTranscriptResponse(const NameltiTranscriptResponse& from);

  inline NameltiTranscriptResponse& operator=(const NameltiTranscriptResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const NameltiTranscriptResponse& default_instance();

  static inline const NameltiTranscriptResponse* internal_default_instance() {
    return reinterpret_cast<const NameltiTranscriptResponse*>(
               &_NameltiTranscriptResponse_default_instance_);
  }

  void Swap(NameltiTranscriptResponse* other);

  // implements Message ----------------------------------------------

  inline NameltiTranscriptResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  NameltiTranscriptResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const NameltiTranscriptResponse& from);
  void MergeFrom(const NameltiTranscriptResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(NameltiTranscriptResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string surface = 1;
  void clear_surface();
  static const int kSurfaceFieldNumber = 1;
  const ::std::string& surface() const;
  void set_surface(const ::std::string& value);
  #if LANG_CXX11
  void set_surface(::std::string&& value);
  #endif
  void set_surface(const char* value);
  void set_surface(const char* value, size_t size);
  ::std::string* mutable_surface();
  ::std::string* release_surface();
  void set_allocated_surface(::std::string* surface);

  // .namelti.server.ResultList results = 2;
  bool has_results() const;
  void clear_results();
  static const int kResultsFieldNumber = 2;
  const ::namelti::server::ResultList& results() const;
  ::namelti::server::ResultList* mutable_results();
  ::namelti::server::ResultList* release_results();
  void set_allocated_results(::namelti::server::ResultList* results);

  // @@protoc_insertion_point(class_scope:namelti.server.NameltiTranscriptResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr surface_;
  ::namelti::server::ResultList* results_;
  mutable int _cached_size_;
  friend struct  protobuf_namelti_2eproto::TableStruct;
};
// -------------------------------------------------------------------


// -------------------------------------------------------------------

class NameltiTranscriptResponses : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:namelti.server.NameltiTranscriptResponses) */ {
 public:
  NameltiTranscriptResponses();
  virtual ~NameltiTranscriptResponses();

  NameltiTranscriptResponses(const NameltiTranscriptResponses& from);

  inline NameltiTranscriptResponses& operator=(const NameltiTranscriptResponses& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const NameltiTranscriptResponses& default_instance();

  static inline const NameltiTranscriptResponses* internal_default_instance() {
    return reinterpret_cast<const NameltiTranscriptResponses*>(
               &_NameltiTranscriptResponses_default_instance_);
  }

  void Swap(NameltiTranscriptResponses* other);

  // implements Message ----------------------------------------------

  inline NameltiTranscriptResponses* New() const PROTOBUF_FINAL { return New(NULL); }

  NameltiTranscriptResponses* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const NameltiTranscriptResponses& from);
  void MergeFrom(const NameltiTranscriptResponses& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(NameltiTranscriptResponses* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<string, .namelti.server.ResultList> responses = 1;
  int responses_size() const;
  void clear_responses();
  static const int kResponsesFieldNumber = 1;
  const ::google::protobuf::Map< ::std::string, ::namelti::server::ResultList >&
      responses() const;
  ::google::protobuf::Map< ::std::string, ::namelti::server::ResultList >*
      mutable_responses();

  // @@protoc_insertion_point(class_scope:namelti.server.NameltiTranscriptResponses)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  typedef ::google::protobuf::internal::MapEntryLite<
      ::std::string, ::namelti::server::ResultList,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 >
      NameltiTranscriptResponses_ResponsesEntry;
  ::google::protobuf::internal::MapField<
      ::std::string, ::namelti::server::ResultList,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > responses_;
  mutable int _cached_size_;
  friend struct  protobuf_namelti_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// NameltiTranscriptRequest

// string query = 1;
inline void NameltiTranscriptRequest::clear_query() {
  query_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& NameltiTranscriptRequest::query() const {
  // @@protoc_insertion_point(field_get:namelti.server.NameltiTranscriptRequest.query)
  return query_.GetNoArena();
}
inline void NameltiTranscriptRequest::set_query(const ::std::string& value) {
  
  query_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:namelti.server.NameltiTranscriptRequest.query)
}
#if LANG_CXX11
inline void NameltiTranscriptRequest::set_query(::std::string&& value) {
  
  query_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:namelti.server.NameltiTranscriptRequest.query)
}
#endif
inline void NameltiTranscriptRequest::set_query(const char* value) {
  
  query_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:namelti.server.NameltiTranscriptRequest.query)
}
inline void NameltiTranscriptRequest::set_query(const char* value, size_t size) {
  
  query_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:namelti.server.NameltiTranscriptRequest.query)
}
inline ::std::string* NameltiTranscriptRequest::mutable_query() {
  
  // @@protoc_insertion_point(field_mutable:namelti.server.NameltiTranscriptRequest.query)
  return query_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* NameltiTranscriptRequest::release_query() {
  // @@protoc_insertion_point(field_release:namelti.server.NameltiTranscriptRequest.query)
  
  return query_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void NameltiTranscriptRequest::set_allocated_query(::std::string* query) {
  if (query != NULL) {
    
  } else {
    
  }
  query_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), query);
  // @@protoc_insertion_point(field_set_allocated:namelti.server.NameltiTranscriptRequest.query)
}

// -------------------------------------------------------------------

// NameltiTranscriptRequests

// repeated string queries = 1;
inline int NameltiTranscriptRequests::queries_size() const {
  return queries_.size();
}
inline void NameltiTranscriptRequests::clear_queries() {
  queries_.Clear();
}
inline const ::std::string& NameltiTranscriptRequests::queries(int index) const {
  // @@protoc_insertion_point(field_get:namelti.server.NameltiTranscriptRequests.queries)
  return queries_.Get(index);
}
inline ::std::string* NameltiTranscriptRequests::mutable_queries(int index) {
  // @@protoc_insertion_point(field_mutable:namelti.server.NameltiTranscriptRequests.queries)
  return queries_.Mutable(index);
}
inline void NameltiTranscriptRequests::set_queries(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:namelti.server.NameltiTranscriptRequests.queries)
  queries_.Mutable(index)->assign(value);
}
inline void NameltiTranscriptRequests::set_queries(int index, const char* value) {
  queries_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:namelti.server.NameltiTranscriptRequests.queries)
}
inline void NameltiTranscriptRequests::set_queries(int index, const char* value, size_t size) {
  queries_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:namelti.server.NameltiTranscriptRequests.queries)
}
inline ::std::string* NameltiTranscriptRequests::add_queries() {
  // @@protoc_insertion_point(field_add_mutable:namelti.server.NameltiTranscriptRequests.queries)
  return queries_.Add();
}
inline void NameltiTranscriptRequests::add_queries(const ::std::string& value) {
  queries_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:namelti.server.NameltiTranscriptRequests.queries)
}
inline void NameltiTranscriptRequests::add_queries(const char* value) {
  queries_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:namelti.server.NameltiTranscriptRequests.queries)
}
inline void NameltiTranscriptRequests::add_queries(const char* value, size_t size) {
  queries_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:namelti.server.NameltiTranscriptRequests.queries)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
NameltiTranscriptRequests::queries() const {
  // @@protoc_insertion_point(field_list:namelti.server.NameltiTranscriptRequests.queries)
  return queries_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
NameltiTranscriptRequests::mutable_queries() {
  // @@protoc_insertion_point(field_mutable_list:namelti.server.NameltiTranscriptRequests.queries)
  return &queries_;
}

// -------------------------------------------------------------------

// ResultList_Result

// string yomi = 1;
inline void ResultList_Result::clear_yomi() {
  yomi_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ResultList_Result::yomi() const {
  // @@protoc_insertion_point(field_get:namelti.server.ResultList.Result.yomi)
  return yomi_.GetNoArena();
}
inline void ResultList_Result::set_yomi(const ::std::string& value) {
  
  yomi_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:namelti.server.ResultList.Result.yomi)
}
#if LANG_CXX11
inline void ResultList_Result::set_yomi(::std::string&& value) {
  
  yomi_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:namelti.server.ResultList.Result.yomi)
}
#endif
inline void ResultList_Result::set_yomi(const char* value) {
  
  yomi_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:namelti.server.ResultList.Result.yomi)
}
inline void ResultList_Result::set_yomi(const char* value, size_t size) {
  
  yomi_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:namelti.server.ResultList.Result.yomi)
}
inline ::std::string* ResultList_Result::mutable_yomi() {
  
  // @@protoc_insertion_point(field_mutable:namelti.server.ResultList.Result.yomi)
  return yomi_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ResultList_Result::release_yomi() {
  // @@protoc_insertion_point(field_release:namelti.server.ResultList.Result.yomi)
  
  return yomi_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ResultList_Result::set_allocated_yomi(::std::string* yomi) {
  if (yomi != NULL) {
    
  } else {
    
  }
  yomi_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), yomi);
  // @@protoc_insertion_point(field_set_allocated:namelti.server.ResultList.Result.yomi)
}

// float score = 2;
inline void ResultList_Result::clear_score() {
  score_ = 0;
}
inline float ResultList_Result::score() const {
  // @@protoc_insertion_point(field_get:namelti.server.ResultList.Result.score)
  return score_;
}
inline void ResultList_Result::set_score(float value) {
  
  score_ = value;
  // @@protoc_insertion_point(field_set:namelti.server.ResultList.Result.score)
}

// -------------------------------------------------------------------

// ResultList

// repeated .namelti.server.ResultList.Result results = 1;
inline int ResultList::results_size() const {
  return results_.size();
}
inline void ResultList::clear_results() {
  results_.Clear();
}
inline const ::namelti::server::ResultList_Result& ResultList::results(int index) const {
  // @@protoc_insertion_point(field_get:namelti.server.ResultList.results)
  return results_.Get(index);
}
inline ::namelti::server::ResultList_Result* ResultList::mutable_results(int index) {
  // @@protoc_insertion_point(field_mutable:namelti.server.ResultList.results)
  return results_.Mutable(index);
}
inline ::namelti::server::ResultList_Result* ResultList::add_results() {
  // @@protoc_insertion_point(field_add:namelti.server.ResultList.results)
  return results_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::namelti::server::ResultList_Result >*
ResultList::mutable_results() {
  // @@protoc_insertion_point(field_mutable_list:namelti.server.ResultList.results)
  return &results_;
}
inline const ::google::protobuf::RepeatedPtrField< ::namelti::server::ResultList_Result >&
ResultList::results() const {
  // @@protoc_insertion_point(field_list:namelti.server.ResultList.results)
  return results_;
}

// -------------------------------------------------------------------

// NameltiTranscriptResponse

// string surface = 1;
inline void NameltiTranscriptResponse::clear_surface() {
  surface_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& NameltiTranscriptResponse::surface() const {
  // @@protoc_insertion_point(field_get:namelti.server.NameltiTranscriptResponse.surface)
  return surface_.GetNoArena();
}
inline void NameltiTranscriptResponse::set_surface(const ::std::string& value) {
  
  surface_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:namelti.server.NameltiTranscriptResponse.surface)
}
#if LANG_CXX11
inline void NameltiTranscriptResponse::set_surface(::std::string&& value) {
  
  surface_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:namelti.server.NameltiTranscriptResponse.surface)
}
#endif
inline void NameltiTranscriptResponse::set_surface(const char* value) {
  
  surface_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:namelti.server.NameltiTranscriptResponse.surface)
}
inline void NameltiTranscriptResponse::set_surface(const char* value, size_t size) {
  
  surface_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:namelti.server.NameltiTranscriptResponse.surface)
}
inline ::std::string* NameltiTranscriptResponse::mutable_surface() {
  
  // @@protoc_insertion_point(field_mutable:namelti.server.NameltiTranscriptResponse.surface)
  return surface_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* NameltiTranscriptResponse::release_surface() {
  // @@protoc_insertion_point(field_release:namelti.server.NameltiTranscriptResponse.surface)
  
  return surface_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void NameltiTranscriptResponse::set_allocated_surface(::std::string* surface) {
  if (surface != NULL) {
    
  } else {
    
  }
  surface_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), surface);
  // @@protoc_insertion_point(field_set_allocated:namelti.server.NameltiTranscriptResponse.surface)
}

// .namelti.server.ResultList results = 2;
inline bool NameltiTranscriptResponse::has_results() const {
  return this != internal_default_instance() && results_ != NULL;
}
inline void NameltiTranscriptResponse::clear_results() {
  if (GetArenaNoVirtual() == NULL && results_ != NULL) delete results_;
  results_ = NULL;
}
inline const ::namelti::server::ResultList& NameltiTranscriptResponse::results() const {
  // @@protoc_insertion_point(field_get:namelti.server.NameltiTranscriptResponse.results)
  return results_ != NULL ? *results_
                         : *::namelti::server::ResultList::internal_default_instance();
}
inline ::namelti::server::ResultList* NameltiTranscriptResponse::mutable_results() {
  
  if (results_ == NULL) {
    results_ = new ::namelti::server::ResultList;
  }
  // @@protoc_insertion_point(field_mutable:namelti.server.NameltiTranscriptResponse.results)
  return results_;
}
inline ::namelti::server::ResultList* NameltiTranscriptResponse::release_results() {
  // @@protoc_insertion_point(field_release:namelti.server.NameltiTranscriptResponse.results)
  
  ::namelti::server::ResultList* temp = results_;
  results_ = NULL;
  return temp;
}
inline void NameltiTranscriptResponse::set_allocated_results(::namelti::server::ResultList* results) {
  delete results_;
  results_ = results;
  if (results) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:namelti.server.NameltiTranscriptResponse.results)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// NameltiTranscriptResponses

// map<string, .namelti.server.ResultList> responses = 1;
inline int NameltiTranscriptResponses::responses_size() const {
  return responses_.size();
}
inline void NameltiTranscriptResponses::clear_responses() {
  responses_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::namelti::server::ResultList >&
NameltiTranscriptResponses::responses() const {
  // @@protoc_insertion_point(field_map:namelti.server.NameltiTranscriptResponses.responses)
  return responses_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::namelti::server::ResultList >*
NameltiTranscriptResponses::mutable_responses() {
  // @@protoc_insertion_point(field_mutable_map:namelti.server.NameltiTranscriptResponses.responses)
  return responses_.MutableMap();
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace server
}  // namespace namelti

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_namelti_2eproto__INCLUDED
