# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: namelti.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "namelti.server.NameltiTranscriptRequest" do
    repeated :queries, :string, 1
  end
  add_message "namelti.server.MapVaule" do
    repeated :dict, :string, 1
  end
  add_message "namelti.server.NameltiTranscriptResponse" do
    map :results, :string, :message, 1, "namelti.server.MapVaule"
  end
end

module Namelti
  module Server
    NameltiTranscriptRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("namelti.server.NameltiTranscriptRequest").msgclass
    MapVaule = Google::Protobuf::DescriptorPool.generated_pool.lookup("namelti.server.MapVaule").msgclass
    NameltiTranscriptResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("namelti.server.NameltiTranscriptResponse").msgclass
  end
end
