# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: namelti.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='namelti.proto',
  package='namelti.server',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rnamelti.proto\x12\x0enamelti.server\"+\n\x18NameltiTranscriptRequest\x12\x0f\n\x07queries\x18\x01 \x03(\t\"\x18\n\x08MapVaule\x12\x0c\n\x04\x64ict\x18\x01 \x03(\t\"\xae\x01\n\x19NameltiTranscriptResponse\x12G\n\x07results\x18\x01 \x03(\x0b\x32\x36.namelti.server.NameltiTranscriptResponse.ResultsEntry\x1aH\n\x0cResultsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\'\n\x05value\x18\x02 \x01(\x0b\x32\x18.namelti.server.MapVaule:\x02\x38\x01\x32z\n\x0eNameltiService\x12h\n\x0f\x43onvertNameList\x12(.namelti.server.NameltiTranscriptRequest\x1a).namelti.server.NameltiTranscriptResponse\"\x00\x62\x06proto3')
)




_NAMELTITRANSCRIPTREQUEST = _descriptor.Descriptor(
  name='NameltiTranscriptRequest',
  full_name='namelti.server.NameltiTranscriptRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='queries', full_name='namelti.server.NameltiTranscriptRequest.queries', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=76,
)


_MAPVAULE = _descriptor.Descriptor(
  name='MapVaule',
  full_name='namelti.server.MapVaule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dict', full_name='namelti.server.MapVaule.dict', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=102,
)


_NAMELTITRANSCRIPTRESPONSE_RESULTSENTRY = _descriptor.Descriptor(
  name='ResultsEntry',
  full_name='namelti.server.NameltiTranscriptResponse.ResultsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='namelti.server.NameltiTranscriptResponse.ResultsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='namelti.server.NameltiTranscriptResponse.ResultsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=207,
  serialized_end=279,
)

_NAMELTITRANSCRIPTRESPONSE = _descriptor.Descriptor(
  name='NameltiTranscriptResponse',
  full_name='namelti.server.NameltiTranscriptResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='results', full_name='namelti.server.NameltiTranscriptResponse.results', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_NAMELTITRANSCRIPTRESPONSE_RESULTSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=279,
)

_NAMELTITRANSCRIPTRESPONSE_RESULTSENTRY.fields_by_name['value'].message_type = _MAPVAULE
_NAMELTITRANSCRIPTRESPONSE_RESULTSENTRY.containing_type = _NAMELTITRANSCRIPTRESPONSE
_NAMELTITRANSCRIPTRESPONSE.fields_by_name['results'].message_type = _NAMELTITRANSCRIPTRESPONSE_RESULTSENTRY
DESCRIPTOR.message_types_by_name['NameltiTranscriptRequest'] = _NAMELTITRANSCRIPTREQUEST
DESCRIPTOR.message_types_by_name['MapVaule'] = _MAPVAULE
DESCRIPTOR.message_types_by_name['NameltiTranscriptResponse'] = _NAMELTITRANSCRIPTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NameltiTranscriptRequest = _reflection.GeneratedProtocolMessageType('NameltiTranscriptRequest', (_message.Message,), dict(
  DESCRIPTOR = _NAMELTITRANSCRIPTREQUEST,
  __module__ = 'namelti_pb2'
  # @@protoc_insertion_point(class_scope:namelti.server.NameltiTranscriptRequest)
  ))
_sym_db.RegisterMessage(NameltiTranscriptRequest)

MapVaule = _reflection.GeneratedProtocolMessageType('MapVaule', (_message.Message,), dict(
  DESCRIPTOR = _MAPVAULE,
  __module__ = 'namelti_pb2'
  # @@protoc_insertion_point(class_scope:namelti.server.MapVaule)
  ))
_sym_db.RegisterMessage(MapVaule)

NameltiTranscriptResponse = _reflection.GeneratedProtocolMessageType('NameltiTranscriptResponse', (_message.Message,), dict(

  ResultsEntry = _reflection.GeneratedProtocolMessageType('ResultsEntry', (_message.Message,), dict(
    DESCRIPTOR = _NAMELTITRANSCRIPTRESPONSE_RESULTSENTRY,
    __module__ = 'namelti_pb2'
    # @@protoc_insertion_point(class_scope:namelti.server.NameltiTranscriptResponse.ResultsEntry)
    ))
  ,
  DESCRIPTOR = _NAMELTITRANSCRIPTRESPONSE,
  __module__ = 'namelti_pb2'
  # @@protoc_insertion_point(class_scope:namelti.server.NameltiTranscriptResponse)
  ))
_sym_db.RegisterMessage(NameltiTranscriptResponse)
_sym_db.RegisterMessage(NameltiTranscriptResponse.ResultsEntry)


_NAMELTITRANSCRIPTRESPONSE_RESULTSENTRY._options = None

_NAMELTISERVICE = _descriptor.ServiceDescriptor(
  name='NameltiService',
  full_name='namelti.server.NameltiService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=281,
  serialized_end=403,
  methods=[
  _descriptor.MethodDescriptor(
    name='ConvertNameList',
    full_name='namelti.server.NameltiService.ConvertNameList',
    index=0,
    containing_service=None,
    input_type=_NAMELTITRANSCRIPTREQUEST,
    output_type=_NAMELTITRANSCRIPTRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_NAMELTISERVICE)

DESCRIPTOR.services_by_name['NameltiService'] = _NAMELTISERVICE

# @@protoc_insertion_point(module_scope)
