# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: namelti.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='namelti.proto',
  package='namelti.server',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rnamelti.proto\x12\x0enamelti.server\")\n\x18NameltiTranscriptRequest\x12\r\n\x05query\x18\x01 \x01(\t\",\n\x19NameltiTranscriptRequests\x12\x0f\n\x07queries\x18\x01 \x03(\t\"g\n\nResultList\x12\x32\n\x07results\x18\x01 \x03(\x0b\x32!.namelti.server.ResultList.Result\x1a%\n\x06Result\x12\x0c\n\x04yomi\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\"Y\n\x19NameltiTranscriptResponse\x12\x0f\n\x07surface\x18\x01 \x01(\t\x12+\n\x07results\x18\x02 \x01(\x0b\x32\x1a.namelti.server.ResultList\"\xb8\x01\n\x1aNameltiTranscriptResponses\x12L\n\tresponses\x18\x01 \x03(\x0b\x32\x39.namelti.server.NameltiTranscriptResponses.ResponsesEntry\x1aL\n\x0eResponsesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12)\n\x05value\x18\x02 \x01(\x0b\x32\x1a.namelti.server.ResultList:\x02\x38\x01\x32\xe2\x01\n\x0eNameltiService\x12\x64\n\x0b\x43onvertName\x12(.namelti.server.NameltiTranscriptRequest\x1a).namelti.server.NameltiTranscriptResponse\"\x00\x12j\n\x0f\x43onvertNameList\x12).namelti.server.NameltiTranscriptRequests\x1a*.namelti.server.NameltiTranscriptResponses\"\x00\x62\x06proto3')
)




_NAMELTITRANSCRIPTREQUEST = _descriptor.Descriptor(
  name='NameltiTranscriptRequest',
  full_name='namelti.server.NameltiTranscriptRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='namelti.server.NameltiTranscriptRequest.query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=74,
)


_NAMELTITRANSCRIPTREQUESTS = _descriptor.Descriptor(
  name='NameltiTranscriptRequests',
  full_name='namelti.server.NameltiTranscriptRequests',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='queries', full_name='namelti.server.NameltiTranscriptRequests.queries', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=120,
)


_RESULTLIST_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='namelti.server.ResultList.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='yomi', full_name='namelti.server.ResultList.Result.yomi', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='namelti.server.ResultList.Result.score', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=225,
)

_RESULTLIST = _descriptor.Descriptor(
  name='ResultList',
  full_name='namelti.server.ResultList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='results', full_name='namelti.server.ResultList.results', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_RESULTLIST_RESULT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=225,
)


_NAMELTITRANSCRIPTRESPONSE = _descriptor.Descriptor(
  name='NameltiTranscriptResponse',
  full_name='namelti.server.NameltiTranscriptResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='surface', full_name='namelti.server.NameltiTranscriptResponse.surface', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='results', full_name='namelti.server.NameltiTranscriptResponse.results', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=316,
)


_NAMELTITRANSCRIPTRESPONSES_RESPONSESENTRY = _descriptor.Descriptor(
  name='ResponsesEntry',
  full_name='namelti.server.NameltiTranscriptResponses.ResponsesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='namelti.server.NameltiTranscriptResponses.ResponsesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='namelti.server.NameltiTranscriptResponses.ResponsesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=427,
  serialized_end=503,
)

_NAMELTITRANSCRIPTRESPONSES = _descriptor.Descriptor(
  name='NameltiTranscriptResponses',
  full_name='namelti.server.NameltiTranscriptResponses',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='responses', full_name='namelti.server.NameltiTranscriptResponses.responses', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_NAMELTITRANSCRIPTRESPONSES_RESPONSESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=319,
  serialized_end=503,
)

_RESULTLIST_RESULT.containing_type = _RESULTLIST
_RESULTLIST.fields_by_name['results'].message_type = _RESULTLIST_RESULT
_NAMELTITRANSCRIPTRESPONSE.fields_by_name['results'].message_type = _RESULTLIST
_NAMELTITRANSCRIPTRESPONSES_RESPONSESENTRY.fields_by_name['value'].message_type = _RESULTLIST
_NAMELTITRANSCRIPTRESPONSES_RESPONSESENTRY.containing_type = _NAMELTITRANSCRIPTRESPONSES
_NAMELTITRANSCRIPTRESPONSES.fields_by_name['responses'].message_type = _NAMELTITRANSCRIPTRESPONSES_RESPONSESENTRY
DESCRIPTOR.message_types_by_name['NameltiTranscriptRequest'] = _NAMELTITRANSCRIPTREQUEST
DESCRIPTOR.message_types_by_name['NameltiTranscriptRequests'] = _NAMELTITRANSCRIPTREQUESTS
DESCRIPTOR.message_types_by_name['ResultList'] = _RESULTLIST
DESCRIPTOR.message_types_by_name['NameltiTranscriptResponse'] = _NAMELTITRANSCRIPTRESPONSE
DESCRIPTOR.message_types_by_name['NameltiTranscriptResponses'] = _NAMELTITRANSCRIPTRESPONSES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NameltiTranscriptRequest = _reflection.GeneratedProtocolMessageType('NameltiTranscriptRequest', (_message.Message,), dict(
  DESCRIPTOR = _NAMELTITRANSCRIPTREQUEST,
  __module__ = 'namelti_pb2'
  # @@protoc_insertion_point(class_scope:namelti.server.NameltiTranscriptRequest)
  ))
_sym_db.RegisterMessage(NameltiTranscriptRequest)

NameltiTranscriptRequests = _reflection.GeneratedProtocolMessageType('NameltiTranscriptRequests', (_message.Message,), dict(
  DESCRIPTOR = _NAMELTITRANSCRIPTREQUESTS,
  __module__ = 'namelti_pb2'
  # @@protoc_insertion_point(class_scope:namelti.server.NameltiTranscriptRequests)
  ))
_sym_db.RegisterMessage(NameltiTranscriptRequests)

ResultList = _reflection.GeneratedProtocolMessageType('ResultList', (_message.Message,), dict(

  Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
    DESCRIPTOR = _RESULTLIST_RESULT,
    __module__ = 'namelti_pb2'
    # @@protoc_insertion_point(class_scope:namelti.server.ResultList.Result)
    ))
  ,
  DESCRIPTOR = _RESULTLIST,
  __module__ = 'namelti_pb2'
  # @@protoc_insertion_point(class_scope:namelti.server.ResultList)
  ))
_sym_db.RegisterMessage(ResultList)
_sym_db.RegisterMessage(ResultList.Result)

NameltiTranscriptResponse = _reflection.GeneratedProtocolMessageType('NameltiTranscriptResponse', (_message.Message,), dict(
  DESCRIPTOR = _NAMELTITRANSCRIPTRESPONSE,
  __module__ = 'namelti_pb2'
  # @@protoc_insertion_point(class_scope:namelti.server.NameltiTranscriptResponse)
  ))
_sym_db.RegisterMessage(NameltiTranscriptResponse)

NameltiTranscriptResponses = _reflection.GeneratedProtocolMessageType('NameltiTranscriptResponses', (_message.Message,), dict(

  ResponsesEntry = _reflection.GeneratedProtocolMessageType('ResponsesEntry', (_message.Message,), dict(
    DESCRIPTOR = _NAMELTITRANSCRIPTRESPONSES_RESPONSESENTRY,
    __module__ = 'namelti_pb2'
    # @@protoc_insertion_point(class_scope:namelti.server.NameltiTranscriptResponses.ResponsesEntry)
    ))
  ,
  DESCRIPTOR = _NAMELTITRANSCRIPTRESPONSES,
  __module__ = 'namelti_pb2'
  # @@protoc_insertion_point(class_scope:namelti.server.NameltiTranscriptResponses)
  ))
_sym_db.RegisterMessage(NameltiTranscriptResponses)
_sym_db.RegisterMessage(NameltiTranscriptResponses.ResponsesEntry)


_NAMELTITRANSCRIPTRESPONSES_RESPONSESENTRY._options = None

_NAMELTISERVICE = _descriptor.ServiceDescriptor(
  name='NameltiService',
  full_name='namelti.server.NameltiService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=506,
  serialized_end=732,
  methods=[
  _descriptor.MethodDescriptor(
    name='ConvertName',
    full_name='namelti.server.NameltiService.ConvertName',
    index=0,
    containing_service=None,
    input_type=_NAMELTITRANSCRIPTREQUEST,
    output_type=_NAMELTITRANSCRIPTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ConvertNameList',
    full_name='namelti.server.NameltiService.ConvertNameList',
    index=1,
    containing_service=None,
    input_type=_NAMELTITRANSCRIPTREQUESTS,
    output_type=_NAMELTITRANSCRIPTRESPONSES,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_NAMELTISERVICE)

DESCRIPTOR.services_by_name['NameltiService'] = _NAMELTISERVICE

# @@protoc_insertion_point(module_scope)
